const SET_ANIMATE_NAME = 'SET_ANIMATE_NAME';
const SET_NAV_INDEX = 'SET_NAV_INDEX';
const JUDGE_IS_NOT_FIRST = 'JUDGE_IS_NOT_FIRST';
export default {
    SET_ANIMATE_NAME,
    SET_NAV_INDEX,
    JUDGE_IS_NOT_FIRST
}
